// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

// import (
// 	"bytes"
// 	"encoding/json"
// 	"strings"

// 	"github.com/alecthomas/template"
// 	"github.com/swaggo/swag"
// )

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pc user"
                ],
                "summary": "创建User",
                "parameters": [
                    {
                        "description": "创建User参数",
                        "name": "创建User参数",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg.UserCreateParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg.UserCreateParam": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "gender": {
                    "description": "性别",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "phone": {
                    "description": "电话",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "API",
	Description: "",
}

type s struct{}

// func (s *s) ReadDoc() string {
// 	sInfo := SwaggerInfo
// 	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

// 	t, err := template.New("swagger_info").Funcs(template.FuncMap{
// 		"marshal": func(v interface{}) string {
// 			a, _ := json.Marshal(v)
// 			return string(a)
// 		},
// 	}).Parse(doc)
// 	if err != nil {
// 		return doc
// 	}

// 	var tpl bytes.Buffer
// 	if err := t.Execute(&tpl, sInfo); err != nil {
// 		return doc
// 	}

// 	return tpl.String()
// }

// func init() {
// 	swag.Register(swag.Name, &s{})
// }
