basePath: /api
definitions:
  pkg.UserCreateParam:
    properties:
      age:
        description: 年龄
        type: integer
      gender:
        description: 性别
        type: string
      name:
        description: 姓名
        type: string
      phone:
        description: 电话
        type: string
    type: object
info:
  contact: {}
  title: API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建User参数
        in: body
        name: 创建User参数
        required: true
        schema:
          $ref: '#/definitions/pkg.UserCreateParam'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            type: string
      summary: 创建User
      tags:
      - pc user
swagger: "2.0"
